#!/bin/bash

# You can call this script like this:
# volumecontrol up
# volumecontrol down
# volumecontrol mute

function get_volume {
   echo "`wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/.* //'`" '* 100' | bc | sed 's/\..*//'
}

function is_mute {
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep [MUTED] > /dev/null
}

#bar=$(seq -s "─" $(($volume/5)) | sed 's/[0-9]//g')

case $1 in
    up)
	# Set the volume on (if it was muted)
	wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 > /dev/null
	# Up the volume (+ 2%)
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+ > /dev/null
	canberra-gtk-play -i audio-volume-change
	;;
    down)
	wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 > /dev/null
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%- > /dev/null
	canberra-gtk-play -i audio-volume-change
	;;
    mute)
    	# Toggle mute
	wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle > /dev/null
	if is_mute ; then
            icon_name="/usr/share/icons/Adwaita/16x16/legacy/audio-volume-medium.png"
	else
	    canberra-gtk-play -i audio-volume-change
	fi
	;;
    set)
	wpctl set-volume @DEFAULT_AUDIO_SINK@ $2%
	canberra-gtk-play -i audio-volume-change
	;;
    get)
	echo $(get_volume)
	;;
    *)
	volume="$(get_volume)"

	if [[ $volume == "100" ]]; then
		icon=""
	elif [[ $volume -ge "89" && $volume -le "100" ]]; then
		icon=""
	elif [[ $volume -ge "79" && $volume -le "90" ]]; then
		icon=""
	elif [[ $volume -ge "69" && $volume -le "80" ]]; then
		icon=""
	elif [[ $volume -ge "59" && $volume -le "70" ]]; then
		icon=""
	elif [[ $volume -ge "49" && $volume -le "60" ]]; then
		icon=""
	elif [[ $volume -ge "39" && $volume -le "50" ]]; then
		icon=""
	elif [[ $volume -ge "29" && $volume -le "40" ]]; then
		icon=""
	elif [[ $volume -ge "19" && $volume -le "30" ]]; then
		icon=""
	elif [[ $volume -ge "9" && $volume -le "20" ]]; then
		icon=""
	elif [[ $volume -gt "0" && $volume -le "10" ]]; then
		icon=""
	elif [[ $volume -eq "0" ]]; then
		icon=""
		volume=""
	fi


if is_mute; then
		icon="󰖁"
		volume="$(get_volume)"
fi

printf "%s" "$icon $volume"
  ;;
esac
